### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by qwergle** [martmists-gh/chess_engine_c#1]
Hi! This looks like a really cool project, but it's missing a license. Could you please add one so that others can contribute to it and use it in their own projects?

**Comment by Martmists-GH** [comment]
I don't think anyone would actually want to use this, there's much better implementations around

**Comment by qwergle** [comment]
Yes, but if it doesn't have a license, then by definition, it's not open source. Regardless of its quality, it should still have a license.

**Comment by Martmists-GH** [comment]
> then by definition, it's not open source

And I don't see a problem with that. You're free to use it as reference as with anything else with source publicly available, but it's still ARR as intended.
